from cores import *

LARGURA = 800
ALTURA = 600

ESPESSURA_FINA   = 2
ESPESSURA_MEDIA  = 3
ESPESSURA_GROSSA = 8

BTT_LARGURA = 35
BTT_ALTURA  = 35
MARGEM = 5          #Distância entre botões do mesmo grupo
GAP    = 25         #Distância entre grupos

LINHA1_Y1 = 8
LINHA1_Y2 = LINHA1_Y1 + BTT_ALTURA
LINHA2_Y1 = LINHA1_Y2 + MARGEM
LINHA2_Y2 = LINHA2_Y1 + BTT_ALTURA
ALTURA_BARRA_NAVEGACAO = LINHA2_Y2 + 8

X_NS    = 8
X_TOOLS = X_NS    + BTT_LARGURA + GAP
X_ESP   = X_TOOLS + (BTT_LARGURA + MARGEM) * 4 + GAP
X_CORES = X_ESP   + BTT_LARGURA + GAP

ALTURA_TOTAL = LINHA2_Y2 - LINHA1_Y1
TERCO = ALTURA_TOTAL // 3

COR_W = 25